"""empty message

Revision ID: 2013c6f90d14
Revises: 0d537c83a490
Create Date: 2019-09-25 06:41:58.609630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2013c6f90d14'
down_revision = '0d537c83a490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('habit_create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'habit_create_date')
    # ### end Alembic commands ###
